# Generated by Django 4.2.2 on 2024-03-11 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="answer_log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(default="", max_length=32, verbose_name="用户"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "statue",
                    models.SmallIntegerField(
                        choices=[(0, "开始作答"), (1, "结束作答")], verbose_name="作答状态"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="dat_test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.CharField(default="", max_length=32, verbose_name="用户"),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "word1",
                    models.CharField(default="", max_length=32, verbose_name="词汇1"),
                ),
                (
                    "word2",
                    models.CharField(default="", max_length=32, verbose_name="词汇2"),
                ),
                (
                    "word3",
                    models.CharField(default="", max_length=32, verbose_name="词汇3"),
                ),
                (
                    "word4",
                    models.CharField(default="", max_length=32, verbose_name="词汇4"),
                ),
                (
                    "word5",
                    models.CharField(default="", max_length=32, verbose_name="词汇5"),
                ),
                (
                    "word6",
                    models.CharField(default="", max_length=32, verbose_name="词汇6"),
                ),
                (
                    "word7",
                    models.CharField(default="", max_length=32, verbose_name="词汇7"),
                ),
                (
                    "word8",
                    models.CharField(default="", max_length=32, verbose_name="词汇8"),
                ),
                (
                    "word9",
                    models.CharField(default="", max_length=32, verbose_name="词汇9"),
                ),
                (
                    "word10",
                    models.CharField(default="", max_length=32, verbose_name="词汇10"),
                ),
                (
                    "dat_score",
                    models.IntegerField(default=0, max_length=32, verbose_name="DAT得分"),
                ),
                (
                    "effective_num",
                    models.IntegerField(default=0, max_length=32, verbose_name="有效词数"),
                ),
            ],
        ),
    ]
