# Generated by Django 4.2.2 on 2024-03-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dat_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dat_test",
            name="dat_score",
            field=models.IntegerField(default=0, verbose_name="DAT得分"),
        ),
        migrations.AlterField(
            model_name="dat_test",
            name="effective_num",
            field=models.IntegerField(default=0, verbose_name="有效词数"),
        ),
    ]
