# Generated by Django 4.2.2 on 2024-03-11 04:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dat_app", "0002_alter_dat_test_dat_score_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dat_test",
            old_name="user",
            new_name="username",
        ),
    ]
