# Generated by Django 4.2.2 on 2024-03-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dat_app", "0004_remove_dat_test_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="dat_test",
            name="username",
            field=models.CharField(default="", max_length=32, verbose_name="用户"),
        ),
    ]
