# Generated by Django 4.2.2 on 2024-03-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dat_app", "0005_dat_test_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="dat_test",
            name="picture_path",
            field=models.CharField(max_length=128, null=True, verbose_name="图片地址"),
        ),
    ]
