# Generated by Django 4.2.2 on 2024-03-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dat_app', '0006_dat_test_picture_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='spend_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=32, verbose_name='用户名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='作答开始时间')),
                ('spend_time', models.CharField(max_length=32, verbose_name='作答时长')),
            ],
        ),
    ]
