# Generated by Django 4.2.2 on 2024-03-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dat_app', '0007_spend_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='task_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=32, verbose_name='发散性思维测试')),
                ('limited_time', models.IntegerField(verbose_name='限制时间单位为s')),
            ],
        ),
    ]
