# Generated by Django 4.2.2 on 2024-03-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dat_app', '0008_task_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='dat_test',
            name='spend_time',
            field=models.CharField(default='无', max_length=32, verbose_name='作答时间'),
        ),
    ]
