# Generated by Django 4.2.2 on 2024-03-24 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dat_app', '0010_alter_dat_test_word1_alter_dat_test_word10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dat_test',
            name='spend_time',
            field=models.CharField(default='无', max_length=32, null=True, verbose_name='作答时间'),
        ),
    ]
