# Generated by Django 4.2.2 on 2024-03-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dat_app', '0011_alter_dat_test_spend_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dat_test',
            name='spend_time',
            field=models.CharField(default='无', max_length=32, verbose_name='作答时间'),
        ),
        migrations.AlterField(
            model_name='dat_test',
            name='word1',
            field=models.CharField(default='', max_length=32, verbose_name='词汇1'),
        ),
        migrations.AlterField(
            model_name='dat_test',
            name='word10',
            field=models.CharField(default='', max_length=32, verbose_name='词汇10'),
        ),
        migrations.AlterField(
            model_name='dat_test',
            name='word2',
            field=models.CharField(default='', max_length=32, verbose_name='词汇2'),
        ),
        migrations.AlterField(
            model_name='dat_test',
            name='word3',
            field=models.CharField(default='', max_length=32, verbose_name='词汇3'),
        ),
        migrations.AlterField(
            model_name='dat_test',
            name='word4',
            field=models.CharField(default='', max_length=32, verbose_name='词汇4'),
        ),
        migrations.AlterField(
            model_name='dat_test',
            name='word5',
            field=models.CharField(default='', max_length=32, verbose_name='词汇5'),
        ),
        migrations.AlterField(
            model_name='dat_test',
            name='word6',
            field=models.CharField(default='', max_length=32, verbose_name='词汇6'),
        ),
        migrations.AlterField(
            model_name='dat_test',
            name='word7',
            field=models.CharField(default='', max_length=32, verbose_name='词汇7'),
        ),
        migrations.AlterField(
            model_name='dat_test',
            name='word8',
            field=models.CharField(default='', max_length=32, verbose_name='词汇8'),
        ),
        migrations.AlterField(
            model_name='dat_test',
            name='word9',
            field=models.CharField(default='', max_length=32, verbose_name='词汇9'),
        ),
    ]
