# Generated by Django 4.2.2 on 2024-04-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dat_app', '0012_alter_dat_test_spend_time_alter_dat_test_word1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dat_test',
            name='limited_time',
            field=models.CharField(default='无', max_length=32, verbose_name='限制时间'),
        ),
    ]
